---
- hosts: "{{target|default('all')}}"
  become: true
  become_user: "{{ deployment_user|default('vagrant') }} -i"
  become_method: "sudo"

  vars_files:
    - vars/main.yml

  tasks:
    - include: tasks/sync.yml

    - block:
      - name: "Load the tick scripts"
        shell: |
          kapacitor define -name aggregate -tick tick/aggregate.tick -type stream -dbrp "sampledb"."default"

      tags: ["load-ticks"]

    - block:
      - name: "Run the test case"
        shell: |
          (influx --execute 'drop measurement actual' --database sampledb || true)  &&
          (influx --execute 'drop measurement expected' --database sampledb || true) &&
          kapacitor replay -id $(cat recording.id) -name aggregate --fast --rec-time &&
          influx --format=csv --execute "select mean(metric1) as metric1 into expected from sample where time >= '2016-03-08 05:00:00' and time < '2016-03-08 08:00:00' group by time(5m), *" --precision=rfc3339 --database=sampledb &&
          influx --format=csv --execute 'select * from actual' --precision=rfc3339 --database=sampledb > actual.csv &&
          influx --format=csv --execute 'select * from expected' --precision=rfc3339 --database=sampledb > expected.csv &&
          diff <(sed "s/expected/actual/" < expected.csv) actual.csv
        args:
          executable: /bin/bash

      tags: ["test-case"]