---
- hosts: "{{target|default('all')}}"
  become: true
  become_user: "{{ deployment_user|default('vagrant') }} -i"
  become_method: "sudo"

  vars:
    build_variant: false
    kapacitor_checkout: master
    influxdb_checkout: master
    projects:
      - project: kapacitor
        checkout: "{{kapacitor_checkout}}"
      - project: influxdb
        checkout: "{{influxdb_checkout}}"

  roles:
    - role: angstwad.docker_ubuntu
      become_user: root
      docker_group_members: ["{{deployment_user|default('vagrant')}}"]

    - role: joshualund.golang
      go_tarball: go1.4.3.linux-amd64.tar.gz
      go_tarball_checksum: sha1:332b64236d30a8805fc8dd8b3a269915b4c507fe
      become_user: root

  tasks:
    - include: tasks/sync.yml

    - name: Add ssh agent line to sudoers
      become_user: root
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: SSH_AUTH_SOCK
        line: Defaults env_keep += "SSH_AUTH_SOCK"
      tags: ["init-sudo"]

    - block:
      - name: "clone influxdb-docker"
        git: repo=https://github.com/influxdata/influxdb-docker.git
             dest=~/influxdb-docker

      - name: "clone kapacitor-docker"
        git: repo=https://github.com/influxdata/kapacitor-docker.git
             dest=~/kapacitor-docker

      - name: "clone influxdb"
        git: repo=https://github.com/influxdata/influxdb.git
             dest=~/go/src/github.com/influxdata/influxdb

      - name: "clone kapacitor"
        git: repo=https://github.com/influxdata/kapacitor.git
             dest=~/go/src/github.com/influxdata/kapacitor
      tags: ["clone"]

    - block:
      - name: "make base influxdb image"
        docker_image:
          path=/home/{{ansible_user}}/influxdb-docker/0.12/
          name=influxdb
          state=present
          tag=latest

      - name: "make base kapacitor image"
        docker_image:
          path=/home/{{ansible_user}}/kapacitor-docker/0.12/
          name=kapacitor
          state=present
          tag=latest

      - name: "initialise default copies"
        shell: |
          docker run --rm -v $(pwd)/services/build:/build --entrypoint=/bin/sh influxdb:latest -c 'cp /usr/bin/influx /build'
          docker run --rm -v $(pwd)/services/build:/build --entrypoint=/bin/sh influxdb:latest -c 'cp /usr/bin/influxd /build'
          docker run --rm -v $(pwd)/services/build:/build --entrypoint=/bin/sh kapacitor:latest -c 'cp /usr/bin/kapacitor /build'
          docker run --rm -v $(pwd)/services/build:/build --entrypoint=/bin/sh kapacitor:latest -c 'cp /usr/bin/kapacitord /build'

      - block:
        - name: "link the influx client"
          file: path=/usr/bin/influx src=/home/{{ansible_user}}/services/build/influx state=link

        - name: "link the kapacitor client"
          file: path=/usr/bin/kapacitor src=/home/{{ansible_user}}/services/build/kapacitor state=link
        tags: ["links"]
        become_user: root

    - block:
      - name: "sync with source"
        shell: |
          cd $GOPATH/src/github.com/influxdata/{{item.project}} &&
          git fetch origin &&
          git checkout {{item.checkout}}
        with_items: "{{projects}}"

      - name: "build influxdb"
        shell: |
            pushd ~/go/src/github.com/influxdata/influxdb &&
            go get -d ./... &&
            popd &&
            mkdir -p services/build &&
            go build -o services/build/influxd github.com/influxdata/influxdb/cmd/influxd &&
            go build -o services/build/influx github.com/influxdata/influxdb/cmd/influx
        args:
          executable: /bin/bash

      - name: "build kapacitor"
        shell: |
            OLDPWD=$(pwd) &&
            mkdir -p services/build &&
            pushd ~/go/src/github.com/influxdata/kapacitor &&
            go get -d ./... &&
            docker run -it -v ${OLDPWD}/services/build:/app/build -v "${GOPATH}":/gopath -v "$(pwd)":/app -e "GOPATH=/gopath" -w /app golang:1.6 sh -c 'go build --ldflags="-s" -o build/kapacitord ./cmd/kapacitord'
            docker run -it -v ${OLDPWD}/services/build:/app/build -v "${GOPATH}":/gopath -v "$(pwd)":/app -e "GOPATH=/gopath" -w /app golang:1.6 sh -c 'go build --ldflags="-s" -o build/kapacitor ./cmd/kapacitor'
        args:
          executable: /bin/bash

      tags: recompile
      when: build_variant

    - block:
      - name: "install csv tools"
        shell: |
          go get -d github.com/wildducktheories/go-csv
          go install github.com/wildducktheories/go-csv/...

      - name: "build composition"
        shell: |
          docker-compose -f ~/services/docker-compose.yml build

      tags: ["build", "recompile"]

    - name: "restart composition after variant build"
      shell: |
        docker-compose -f ~/services/docker-compose.yml down
        docker-compose -f ~/services/docker-compose.yml up -d
      when: build_variant
      tags: ["recompile"]

    - block:
      - name: "start"
        shell: |
          cd ~/services &&
          docker-compose up -d &&
          sleep 5

      tags: ["start"]

    - block:
      - name: "Load the sample data (load-data)"
        shell: |
          influx -execute 'create database sampledb' &&
          curl --data-binary @- "http://localhost:8086/write?db=sampledb&precision=ns" < test-data/load.influx
      tags: ["load-data"]
