- block:
  - name: synchronize
    synchronize: src=files/ dest=~/ archive=no

  - name: ownership
    file: path=/home/{{ansible_user}}/ owner={{ansible_user}} group={{ansible_user}} recurse=yes
    become_user: root
  tags: ["sync"]

